"Area:Accessibility":
  - '\[[xX]\]\s*Accessibility'
"Area:Core":
  - '\[[xX]\]\s*Core'
"Area:Data":
  - '\[[xX]\]\s*Data'
"Area:Events":
  - '\[[xX]\]\s*Events'
"Area:IO":
  - '\[[xX]\]\s*IO'
"Area:Utilities":
  - '\[[xX]\]\s*Utilities'
"Build Process":
  - '\[[xX]\]\s*Build Process'
"Unit Testing":
  - '\[[xX]\]\s*Unit Testing'
"Internalization":
  - '\[[xX]\]\s*Internalization'
"Friendly Errors":
  - '\[[xX]\]\s*Friendly Errors'
